create table if not exists rsvp (
  id bigint generated by default as identity primary key,
  nome text not null,
  acompanhantes integer default 0,
  presenca text not null,
  mensagem text,
  created_at timestamptz default now()
);
create table if not exists presentes (
  id bigint generated by default as identity primary key,
  nome text not null,
  categoria text,
  valor numeric(10,2),
  reservado boolean default false,
  reservado_por text,
  reservado_em timestamptz
);
create table if not exists recados (
  id bigint generated by default as identity primary key,
  nome text not null,
  mensagem text not null,
  created_at timestamptz default now()
);
